version: '3'
services:
  redis:
    image: redis:alpine3.16
    container_name: monita-redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=monita
  mysql:
    image: yobasystems/alpine-mariadb
    container_name: monita-mysql
    environment:
      MYSQL_ROOT_PASSWORD: monita
      MYSQL_DATABASE: monita
      MYSQL_USER: monita
      MYSQL_PASSWORD: monita
    ports:
      - "3306:3306"
    restart: always
